// src/data/videoStyles.js
export const VIDEO_STYLES = [
  {
    id: 'cinematic',
    title: 'Cinematic',
    description: 'Hollywood-quality motion with dramatic lighting and depth',
    gradient: 'linear-gradient(135deg, #1a1a2e, #16213e, #0f3460)',
    emoji: '🎬',
    prompt: 'cinematic motion, film grain, dramatic lighting, shallow depth of field, professional cinematography',
  },
  {
    id: 'slow_motion',
    title: 'Slow Motion',
    description: 'Silky smooth slow-motion with ultra detail',
    gradient: 'linear-gradient(135deg, #0f2027, #203a43, #2c5364)',
    emoji: '🌊',
    prompt: 'slow motion, ultra smooth, high frame rate, fluid movement, graceful motion',
  },
  {
    id: 'dreamy',
    title: 'Dreamy',
    description: 'Soft ethereal motion with glowing haze',
    gradient: 'linear-gradient(135deg, #667eea, #764ba2)',
    emoji: '✨',
    prompt: 'dreamy motion, soft glow, ethereal atmosphere, hazy bokeh, fantasy lighting',
  },
  {
    id: 'hyper_realistic',
    title: 'Hyper Realistic',
    description: 'Ultra realistic motion indistinguishable from real footage',
    gradient: 'linear-gradient(135deg, #232526, #414345)',
    emoji: '📷',
    prompt: 'hyper realistic, photorealistic motion, real camera movement, natural lighting, 8K quality',
  },
  {
    id: 'fashion',
    title: 'Fashion',
    description: 'High-end fashion editorial with runway motion',
    gradient: 'linear-gradient(135deg, #c94b4b, #4b134f)',
    emoji: '👗',
    prompt: 'fashion editorial motion, runway walk, high fashion, vogue style, editorial lighting',
  },
  {
    id: 'glamour',
    title: 'Glamour',
    description: 'Luxurious glam aesthetic with beautiful lighting',
    gradient: 'linear-gradient(135deg, #f7971e, #ffd200)',
    emoji: '💫',
    prompt: 'glamour motion, golden hour lighting, luxurious aesthetic, beauty editorial, glowing skin',
  },
  {
    id: 'dark_aesthetic',
    title: 'Dark Aesthetic',
    description: 'Moody dark tones with atmospheric shadows',
    gradient: 'linear-gradient(135deg, #0a0a0a, #1a1a1a, #2d1b4e)',
    emoji: '🖤',
    prompt: 'dark aesthetic motion, moody shadows, deep contrast, mysterious atmosphere, noir lighting',
  },
  {
    id: 'golden_hour',
    title: 'Golden Hour',
    description: 'Warm golden sunlight with glowing motion',
    gradient: 'linear-gradient(135deg, #f83600, #f9d423)',
    emoji: '🌅',
    prompt: 'golden hour motion, warm sunlight, orange glow, sunset atmosphere, lens flare',
  },
  {
    id: 'neon_nights',
    title: 'Neon Nights',
    description: 'Vibrant neon city lights with nighttime energy',
    gradient: 'linear-gradient(135deg, #12c2e9, #c471ed, #f64f59)',
    emoji: '🌃',
    prompt: 'neon lights motion, cyberpunk atmosphere, city night, vivid colors, neon glow',
  },
  {
    id: 'studio',
    title: 'Studio',
    description: 'Clean professional studio look with perfect lighting',
    gradient: 'linear-gradient(135deg, #2c3e50, #3498db)',
    emoji: '🎥',
    prompt: 'studio motion, clean background, professional lighting, commercial quality, sharp focus',
  },
];
