FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

WORKDIR /app

# Install missing system libraries
RUN apt-get update && apt-get install -y \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*


RUN pip install --no-cache-dir "numpy==1.26.4"

RUN pip install --no-cache-dir \
    diffusers==0.27.0 \
    transformers==0.38.0 \
    accelerate==0.27.0 \
    safetensors==0.4.2 \
    runpod==1.6.2 \
    Pillow==10.2.0 \
    requests==2.31.0 \
    controlnet-aux==0.0.7 \
    timm \
    mediapipe \
    huggingface_hub==0.20.3 \
    opencv-python-headless==4.9.0.80

# Force numpy back down after everything installed
RUN pip install --no-cache-dir --force-reinstall "numpy==1.26.4"

ARG CIVITAI_TOKEN
ARG HF_TOKEN

COPY download_models_edit.py .
RUN CIVITAI_TOKEN=${CIVITAI_TOKEN} HF_TOKEN=${HF_TOKEN} python download_models_edit.py

COPY handler_edit.py .

RUN python -c "import torch; print('torch OK')"
RUN python -c "from diffusers import StableDiffusionXLControlNetPipeline, ControlNetModel; print('diffusers OK')"
RUN python -c "from controlnet_aux import OpenposeDetector; print('controlnet_aux OK')"
RUN python -c "import runpod; print('runpod OK')"
RUN python -c "import cv2; print('cv2 OK')"

CMD ["python", "handler_edit.py"]
